AllCops:
  NewCops: enable
  Exclude: 
  - 'features/support/factory/static/*'
  - 'features/support/utils/schemas/*'
  - 'features/support/env.rb'
Naming/AccessorMethodName:
  Enabled: false
Style/Documentation:
  Enabled: false
Naming/AsciiIdentifiers:
  Enabled: false
Style/GlobalVars:
  Enabled: false
Layout/LineLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
